<style>
@import url(https://www.numfys.net/static/css/nbstyle.css);
</style>
<a href="https://www.numfys.net"><img class="logo" /></a>

# Линейная алгебра в Python

### Modules - Basics
<section class="post-meta">
By Henning G. Hugdal, Håkon W. Ånes and Jon Andreas Støvneng
</section>
Last edited: February 7th 2018 
___

Несмотря на то, что матричные операции могут быть не так естественно встроены в Python, как, например, в MATLAB, Python можно использовать для решения задач линейной алгебры. В дополнение к функциям в базовой библиотеке `numpy`, `numpy` также имеет свой собственный пакет линейной алгебры под названием `linalg`. В этом модуле мы рассмотрим, как `numpy` и `linalg` можно использовать для обработки матриц. Прежде всего, нам нужно импортировать `numpy` и `linalg`:

In [1]:
import numpy as np
import numpy.linalg as la

### Основные операции

Давайте сначала определим две матрицы $A$ и $B$ с помощью массивов `numpy`:

In [2]:
A = np.array([[1, 2],
              [1, 2]])
B = np.array([[2, 1],
             [1, 2]])

Чтобы выполнить матричное умножение $A$ и $B$, мы используем функцию `numpy` `inner(A, B)`:

In [3]:
print(np.inner(A, B))

[[4 5]
 [4 5]]


Степени матрицы могут быть вычислены с помощью `linalg.matrix_powers(A,n)`, где $n$ - целочисленная степень.

In [4]:
print(la.matrix_power(A, 2))

[[3 6]
 [3 6]]


### Решение линейных систем уравнений

Линейные системы уравнений $A\vec{x}=b$ могут быть решены с помощью функции `linalg.solve(A,b)`, которая возвращает вектор $\vec{x}$. В качестве примера давайте решим систему уравнений
$$\begin{align}
2x + y - z &= 8\\
-3x - y + 2z &= -11\\
-2x + y + 2z &= -3,
\end{align}$$

In [5]:
A = np.array([[2, 1, -1],
             [-3, -1, 2],
             [-2, 1, 2]])
b = np.array([8, -11, -3])

x = la.solve(A, b)
print(x)

[ 2.  3. -1.]


Мы видим, что решение $x=2$, $y=3$ и $z=-1$. Мы также могли бы решить СЛАУ, вычислив обратную величину $A$ и умножив ее на $b$. Обратная величина $A$ может быть вычислена с помощью `linalg.inv(A)`.

In [6]:
A_inv = la.inv(A)
x = np.inner(A_inv, b)
print(x)

[ 2.  3. -1.]


Совпало!

### Задачи на собственные значения

Пакет `linalg` также может быть использован для поиска собственных значений и собственных векторов матрицы, то есть вектора $\vec{x}$ матрицы $A$, который удовлетворяет соотношению
$$ A\vec{x} = a \vec{x},$$
где $a$ - константа. Давайте определим собственные значения и собственные векторы матрицы $B$, определенной выше.

In [7]:
(a, x) = la.eig(B)
print("Eigenvalues:\n", a)
print("Eigenvectors:")
for i in range(len(x)):
    print(x[:, i])

Eigenvalues:
 [3. 1.]
Eigenvectors:
[0.70710678 0.70710678]
[-0.70710678  0.70710678]


Из вышесказанного мы видим, что $B$ имеет собственные значения $3$ и $1$ с собственными векторами $[1, 1]/\sqrt{2}$ и $[-1,1]/\sqrt{2}$ соответственно. Функция `eig` возвращает массив $a$ собственных значений и массив $x$ с нормализованными собственными векторами, так что вектор `x[:,i]` соответствует собственному значению `a[i]`.

Выше приведены лишь некоторые из различных функций, доступных в библиотеках `numpy` и `linalg`. Для получения дополнительной информации см. cсылку на документацию ниже.

### References
[1] [Documentation](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html) of the Numpy Linear Algebra package.